version: '3'

services:
  db:
    build:
      context: ./images/postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_ANON_ROLE=${DB_ANON_ROLE}
      - DB_SCHEMA=${DB_SCHEMA}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    restart: always

  elasticsearch:
    build:
      context: ./images/elasticsearch
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      node.name: es01
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.host: 0.0.0.0
      http.port: 9200
      http.cors.enabled: true
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: true
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data: