version: "3.9"

services:
  db:
    build:
      context: ./postgres
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5
      timeout: 5s

  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
      node.name: es01
      cluster.name: es-docker-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.host: 0.0.0.0
      http.port: 9200
      http.cors.enabled: true
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: true
      ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  api:
    build:
      context: ./backend
      dockerfile: Tabarato.Api/Dockerfile
    container_name: api
    environment:
      - DOTNET_ENVIRONMENT=Development
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    ports:
      - "5032:8080"
      - "5443:443"

volumes:
  postgres_data:
  elasticsearch_data: